
import React, { useState } from 'react';
import { generateMarketingCopy } from '../services/geminiService';

export const AIDemo: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [result, setResult] = useState<{ headline: string, description: string } | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;
    
    setLoading(true);
    const data = await generateMarketingCopy(topic);
    setResult(data);
    setLoading(false);
  };

  return (
    <section id="ai-demo" className="py-24 bg-gray-900 text-white overflow-hidden relative">
      <div className="absolute top-0 right-0 w-1/2 h-full bg-indigo-500/10 skew-x-12 translate-x-1/2"></div>
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          <div>
            <h2 className="text-4xl font-extrabold mb-6 leading-tight">
              Let AI Write Your <br />
              <span className="text-indigo-400">Marketing Strategy</span>
            </h2>
            <p className="text-gray-400 text-lg mb-10 leading-relaxed">
              Experience the power of Gemini 3. Enter a business topic below and watch as it generates high-converting landing page copy in real-time.
            </p>
            
            <form onSubmit={handleGenerate} className="flex flex-col sm:flex-row gap-4">
              <input 
                type="text" 
                placeholder="e.g. Sustainable Yoga Mats" 
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-6 py-4 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all text-white"
              />
              <button 
                type="submit" 
                disabled={loading}
                className={`px-8 py-4 bg-indigo-600 rounded-lg font-bold hover:bg-indigo-700 transition-all flex items-center justify-center min-w-[160px] ${loading ? 'opacity-50 cursor-not-allowed' : ''}`}
              >
                {loading ? (
                  <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                ) : 'Magic Copy'}
              </button>
            </form>
          </div>

          <div className="bg-gray-800 p-8 md:p-12 rounded-3xl border border-gray-700 shadow-2xl min-h-[300px] flex flex-col justify-center">
            {result ? (
              <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                <h3 className="text-2xl md:text-3xl font-bold mb-4 text-white">{result.headline}</h3>
                <p className="text-gray-400 text-lg leading-relaxed">{result.description}</p>
                <div className="mt-8 flex items-center space-x-2 text-indigo-400 font-medium">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  <span>Generated by Gemini 3</span>
                </div>
              </div>
            ) : (
              <div className="text-center text-gray-500 italic">
                {loading ? "Crafting your message..." : "Your AI-generated copy will appear here."}
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};
